# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6f42455f-5dcc-4a84-b900-55939cbdd004";
      fsType = "btrfs";
      options = [ "subvol=nixos-root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6f42455f-5dcc-4a84-b900-55939cbdd004";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6f42455f-5dcc-4a84-b900-55939cbdd004";
      fsType = "btrfs";
      options = [ "subvol=nixos-nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B36-E940";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
